id: I8485F9CB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T04:49:24+00:00'
last_modified: '2022-06-08T08:11:50.552058+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8610
  title: རྒྱན་འགྲེལ་སྤྱི་དོན་རོལ་མཚོ།（ཀྲུང་གོ་བོད་ཀྱི་ཤེས་རིག་དཔེ་སྐྲུན་ཁང་／）
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    5FA2:
      image_group_id: I1PD36357
      title: ''
      total_pages: 658
      order: 1
      base_file: 5FA2.txt
    72A8:
      image_group_id: I1PD36358
      title: ''
      total_pages: 676
      order: 2
      base_file: 72A8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
